#!/usr/bin/env node

/**
 * Setup Helper - Checks configuration and creates env.js
 */

const fs = require('fs');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('================================================');
console.log('   ARTI Terminal - Setup Helper');
console.log('================================================\n');

// Check if env.js exists
if (fs.existsSync('env.js')) {
  console.log('✓ env.js already exists\n');

  const content = fs.readFileSync('env.js', 'utf8');

  // Check configuration
  console.log('Current Configuration:');
  console.log('----------------------');

  if (content.includes("window.GEMINI_API_KEY = ''") || content.includes('AIza')) {
    const hasKey = !content.includes("window.GEMINI_API_KEY = ''");
    console.log(`Gemini API Key: ${hasKey ? '✓ Set' : '✗ Not set'}`);
  }

  if (content.includes('localhost:3001/slack')) {
    console.log('Slack URL: ✓ Using proxy (correct for local dev)');
  } else if (content.includes('hooks.slack.com')) {
    console.log('Slack URL: ✗ Using direct webhook (will fail due to CORS)');
    console.log('\n⚠️  WARNING: Change to http://localhost:3001/slack');
  } else {
    console.log('Slack URL: ✗ Not set');
  }

  console.log('\n');
  rl.question('Do you want to reconfigure? (y/N): ', (answer) => {
    if (answer.toLowerCase() === 'y') {
      runSetup();
    } else {
      checkSlackProxy();
    }
  });
} else {
  console.log('env.js not found. Let\'s create it!\n');
  runSetup();
}

function runSetup() {
  console.log('\n================================================');
  console.log('   Configuration Setup');
  console.log('================================================\n');

  rl.question('Enter your Gemini API Key (or press Enter to skip): ', (geminiKey) => {
    rl.question('Enter your Slack Webhook URL (or press Enter to skip): ', (slackUrl) => {

      const envContent = `// Local environment configuration
// Generated by setup.js

window.GEMINI_API_KEY = '${geminiKey || ''}';  // Get from: https://makersuite.google.com/app/apikey

// For local development, use the proxy server (runs on port 3001)
// This bypasses CORS restrictions when testing locally
window.SLACK_WEBHOOK_URL = 'http://localhost:3001/slack';

// Note: The actual Slack webhook URL should be set in slack-proxy.js
`;

      fs.writeFileSync('env.js', envContent);
      console.log('\n✓ env.js created successfully!\n');

      if (slackUrl && slackUrl.includes('hooks.slack.com')) {
        updateSlackProxy(slackUrl);
      } else {
        checkSlackProxy();
      }
    });
  });
}

function updateSlackProxy(webhookUrl) {
  console.log('\nUpdating slack-proxy.js...');

  let proxyContent = fs.readFileSync('slack-proxy.js', 'utf8');

  // Replace the webhook URL
  proxyContent = proxyContent.replace(
    /const SLACK_WEBHOOK_URL = .+;/,
    `const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL || '${webhookUrl}';`
  );

  fs.writeFileSync('slack-proxy.js', proxyContent);
  console.log('✓ slack-proxy.js updated with your webhook URL\n');

  finish();
}

function checkSlackProxy() {
  console.log('\nChecking slack-proxy.js configuration...');

  const proxyContent = fs.readFileSync('slack-proxy.js', 'utf8');

  if (proxyContent.includes('YOUR_WEBHOOK_URL_HERE')) {
    console.log('✗ Slack webhook URL not set in slack-proxy.js');
    console.log('\nPlease edit slack-proxy.js and replace YOUR_WEBHOOK_URL_HERE');
    console.log('with your actual Slack webhook URL.\n');
  } else {
    console.log('✓ Slack proxy appears to be configured\n');
  }

  finish();
}

function finish() {
  console.log('================================================');
  console.log('   Setup Complete!');
  console.log('================================================\n');
  console.log('Next steps:');
  console.log('1. Run: npm start');
  console.log('2. Open: http://localhost:3000');
  console.log('3. Test Slack by typing /exit in terminal\n');

  rl.close();
}
